site_name: FF's Notebooks
site_url: https://fightingff.github.io/notebooks
nav:
  - Home: index.md
  - Courses:
      - x86 Asm: ASM.md
      - Digit Logic Design: DigitLogic.md
      - CS 231n: CS231n.md
      - ADS: ADS.md
  - Tools:
      - Git: Git.md
theme:
  name: material
  highlightjs: true
  hljs_style: atom-one-dark
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
