site_name: FF's Notebooks
site_url: https://fightingff.github.io/notebooks
nav:
  - Home: index.md
  - Courses:
      - x86 Asm: ASM.md
      - Digit Logic Design: DigitLogic.md
      - CS 231n: CS231n.md
      - ADS: ADS.md
      - OOP: OOP.md
      - Info: Info.md
  - Tools:
      - Git: Git.md
      - Makefile & CMake: Make.md

theme:
  name: material
  highlightjs: true
  hljs_style: atom-one-dark

extra_css:
    - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
