site_name: FF's Notebooks
site_url: https://fightingff.github.io/notebooks

# Repository
repo_name: 'fightingff/notebooks'
repo_url: 'https://github.com/fightingff/notebooks'

nav:
  - Home: index.md
  - ZJU CS Masters' Notes: https://isshikihugh.github.io/zju-cs-asio/
  - Courses:
      - 大一:
        - x86 Asm: ASM.md
      - 大二上:
        - Digit Logic Design: DigitLogic.md
        - CS 231n: CS231n.md
      - 大二下:
        - ADS: ADS.md
        - OOP: OOP.md
        - Information Theory: Info.md
        - Database: Database.md
        - Computer Organization: RiscV.md
  - Tools:
      - Git: Git.md
      - Makefile & CMake: Make.md
  - Materials:
      - AI Materials: AI_Materials.md
      - My AI Repository: https://github.com/fightingff/AI

theme:
  name: material
  highlightjs: true
  hljs_style: atom-one-dark
  features:
    - content.code.copy

extra_css:
    - stylesheets/extra.css
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/gh/wsqstar/ResHosting@0.031/build/js/Sakura.js

plugins:
  - statistics